### ISSUE TITLE
It doesn't work on WIN11.

### ISSUE THREAD

**Issue by xumt448709722** [brianferguson/SysColor.dll#1]
Hi, there, sorry to bother you. I recently found that the SysColor.dll is invalid after I updated the OS version, which is currently WIN11 21H2. I noticed that this project was updated in 2014, so it is possible you can fix this problem for the latest WIN OS. ThX.

**Comment by brianferguson** [comment]
What do you mean by `invalid` ?

Although I haven't had time to fully test the plugin with Windows 11, it seems to load fine and retrieve some of the correct colors.

Can you describe what exactly isn't working for you?
Which `ColorType` option do not work for you?

Can you provide some simple skin code that demonstrates the issues you are having?

-Brian

**Comment by xumt448709722** [comment]
Hi, Brian. Thank you for replying to me.  Attached please find the skin code I used and two pics about when it works and not. The main problem is SysColor.dll cannot get the theme color and only retrieve white, which I think is a default setting.
[0 - APHRODITE.zip](https://github.com/brianferguson/SysColor.dll/files/9597187/0.-.APHRODITE.zip)
![right](https://user-images.githubusercontent.com/33708354/190976581-80a61736-bc38-4527-a909-74ca5a54cf0b.png)
![wrong](https://user-images.githubusercontent.com/33708354/190976599-59e84f1b-d0ef-4e9f-ae49-9813385ed46a.png)

**Comment by xumt448709722** [comment]
Hi, Brian. Thank you for replying to me.  Attached please find the skin code I used and two pics about when it works and not. The main problem is SysColor.dll cannot get the theme color and only retrieve white, which I think is a default setting.
[0 - APHRODITE.zip](https://github.com/brianferguson/SysColor.dll/files/9597187/0.-.APHRODITE.zip)
![right](https://user-images.githubusercontent.com/33708354/190976581-80a61736-bc38-4527-a909-74ca5a54cf0b.png)
![wrong](https://user-images.githubusercontent.com/33708354/190976599-59e84f1b-d0ef-4e9f-ae49-9813385ed46a.png)

**Comment by brianferguson** [comment]
Sorry it took so long to respond. I decided to update the plugin, and added an option for accent color of Windows 10/11.

You can get it here: [https://github.com/brianferguson/SysColor.dll/releases](https://github.com/brianferguson/SysColor.dll/releases)

Just to be clear though, all the previous values worked just fine in Windows 11. The `ColorType=Win8` was not the accent color. It is the active "window" color introduced in Windows 8. I think this is still the color Windows uses to draw the border of an active window, at least it seems to be for me.

So anyway, there is now a new type `ColorType=Accent` is available. This is probably the color you wanted.

-Brian

**Comment by brianferguson** [comment]
Sorry it took so long to respond. I decided to update the plugin, and added an option for accent color of Windows 10/11.

You can get it here: [https://github.com/brianferguson/SysColor.dll/releases](https://github.com/brianferguson/SysColor.dll/releases)

Just to be clear though, all the previous values worked just fine in Windows 11. The `ColorType=Win8` was not the accent color. It is the active "window" color introduced in Windows 8. I think this is still the color Windows uses to draw the border of an active window, at least it seems to be for me.

So anyway, there is now a new type `ColorType=Accent` is available. This is probably the color you wanted.

-Brian

**Comment by xumt448709722** [comment]
Hi， Brian
Thanks so much for helping me out. It does work again.
